### ISSUE TITLE
Explain key flags for each of the EL and CL clients?

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#244]
## Objective

- [ ] Explain key flags for each of the EL and CL clients

## Todos

- [ ] Ethstats flags?
- [ ] AuRa flags?

## Nethermind 

See post below from Ariel on the xDai Validators chat for some useful ports

```
version: '3.7'
services:
  nethermind:
    init: true
    container_name: xdai-validator
    image: nethermind/nethermind:1.14.5
    command:
     - '--JsonRpc.Enabled'
     - 'true'
     - '--Metrics.Enabled'
     - 'true'
     - '--Metrics.ExposePort'
     - '9101'
     - '--Init.MemoryHint'
     - '4000000000'
    environment:
      NETHERMIND_CONFIG: xdai
      NETHERMIND_AURACONFIG_FORCESEALING: "true"
      NETHERMIND_AURACONFIG_TXPRIORITYCONTRACTADDRESS: "0x5f849Fee27a1029fA5bDFA610677f95a82B47Eb8"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://ethstats.gnosischain.com/api"
      NETHERMIND_ETHSTATSCONFIG_SECRET: "4d8fa58363d3990b6a43590945908904cdb556815c5d7bd031771b86dec99d59"
      NETHERMIND_ETHSTATSCONFIG_CONTACT: 
      NETHERMIND_ETHSTATSCONFIG_NAME: "Messi"
      NETHERMIND_INITCONFIG_ISMINING: "true"
      NETHERMIND_INITCONFIG_STORERECEIPTS: "false"
      NETHERMIND_KEYSTORECONFIG_TESTNODEKEY: $KEY
      NETHERMIND_METRICSCONFIG_ENABLED: "true"
      NETHERMIND_METRICSCONFIG_NODENAME: "Messi"
      NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL: https://metrics.nethermind.io/metrics/validators-Ifa0eigee0de.....
      NETHERMIND_METRICSCONFIG_INTERVALSECONDS: 30
#      NETHERMIND_MININGCONFIG_MINGASPRICE: "1000000000"
      NETHERMIND_MININGCONFIG_MINGASPRICE: "999999992"
#      NETHERMIND_MININGCONFIG_TARGETBLOCKGASLIMIT: "17000000"
      NETHERMIND_MININGCONFIG_TARGETBLOCKGASLIMIT: "30000000"
#      NETHERMIND_NETWORKCONFIG_ACTIVEPEERSMAXCOUNT: "100"
      NETHERMIND_PRUNINGCONFIG_ENABLED: "false"
      NETHERMIND_SEQCONFIG_MINLEVEL: "Info"
      NETHERMIND_SEQCONFIG_SERVERURL: "https://seq.nethermind.io"
      NETHERMIND_SEQCONFIG_APIKEY: $SEQAPIKEY
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_SYNCCONFIG_FASTBLOCKS: "true"
      NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC: "false"
      NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC: "false"
```
